name: CI

on: [push]

jobs:
  build:

    runs-on: [self-hosted, macos]

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote
        mkdir build && cd build
        cmake ..
        make -j8
